driver:
  name: vagrant
  network:
    - ["private_network", {ip: "10.11.11.17"}]

provisioner:
  name: chef_zero
  log_level: <%= ENV['CHEF_LOG_LEVEL'] || 'info' %>
  # deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
      box: bento/ubuntu-16.04

suites:
  - name: servernode
    provisioner:
      client_rb:
        environment: development
    driver:
      vm_hostname: zf2tutorial.zf2.dev
    run_list:
      - recipe[zf2::servernode]
    attributes:
      mysql:
        server_root_password: 'rootpass'

