---
driver:
  name: vagrant
  require_chef_omnibus: 12.4.3
  customize:
    memory: 1024

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: servernode
    provisioner:
      client_rb:
        environment: development
    driver:
      vm_hostname: zf2tutorial.zf2.dev
      network:
      - ["private_network", {ip: "10.11.11.17"}]
      customize:
        memory: 1024
    run_list:
      - 'recipe[zf2::servernode]'

