---

driver:
  name: vagrant
  network:
    - ["private_network", {ip: "10.11.11.17"}]

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-14.04
  driver:
    customize:
      memory: 1024
  driver_config:
    box: opscode-ubuntu-14.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box

- name: ubuntu-16.04
  driver_config:
    box: opscode-ubuntu-16.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-16.04_chef-provisionerless.box

suites:
  - name: servernode
    provisioner:
      client_rb:
        environment: development
    driver:
      vm_hostname: zf2tutorial.zf2.dev
    run_list:
      - recipe[zf2::servernode]
    attributes:
      awesome_customers_ubuntu:
        database:
          root_password: 'rootpass'
          admin_password: 'mysql_admin_password'

