driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_version: <%= ENV['CHEF_VERSION'] || 'current' %>
  volumes: [ '/mnt' ]

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
- name: ubuntu-14.04
  driver:
    image: dokken/ubuntu-14.04
    pid_one_command: /sbin/init
    privileged: true
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: ubuntu-16.04
  driver:
    image: dokken/ubuntu-16.04
    pid_one_command: /bin/systemd
    privileged: true
    intermediate_instructions:
      - RUN /usr/bin/apt-get update


suites:
  - name: servernode
    provisioner:
      client_rb:
        environment: testing
    driver:
      vm_hostname: zf2tutorial.zf2.dev
    run_list:
      - recipe[zf2::servernode]
