---

driver:
  name: vagrant
  network:
    - ["private_network", {ip: "10.11.11.17"}]
#    - ["private_network", {ip: "192.168.34.34"}]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver:
      customize:
        memory: 512

suites:
  - name: servernode
    provisioner:
      client_rb:
        environment: development
    driver:
      vm_hostname: zf2tutorial.zf2.dev
    run_list:
      - recipe[zf2::servernode]
    attributes:
      awesome_customers_ubuntu:
        database:
          root_password: 'rootpass'
          admin_password: 'mysql_admin_password'

