sudo: required
dist: trusty

# install the pre-release chef-dk.  Use chef-stable-trusty to install the stable release
addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

services: docker

env:
  matrix:
  - INSTANCE=servernode-ubuntu-1604
  - INSTANCE=servernode-ubuntu-1404

install: echo "skip bundle install"

# Ensure we make ChefDK's Ruby the default
before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/embedded/bin/chef gem install kitchen-docker
script:
  - KITCHEN_LOCAL_YAML=.kitchen.docker.yml /opt/chefdk/embedded/bin/kitchen list
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/rubocop --version
  - /opt/chefdk/embedded/bin/foodcritic --version
  - /opt/chefdk/embedded/bin/foodcritic -f correctness .
#  - KITCHEN_LOCAL_YAML=.kitchen.docker.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}
#  - /opt/chefdk/embedded/bin/rubocop
#  - /opt/chefdk/embedded/bin/foodcritic . --exclude spec
#  - /opt/chefdk/embedded/bin/rspec

branches:
  only:
    - master
