rvm:
  - 2.1
cache:
  - bundler

before_script:
  - bundle exec berks install
script:
  - bundle exec foodcritic -f correctness .
  - bundle exec rubocop
  - bundle exec rspec
branches:
  only:
    - master
