rvm: 2.2

sudo: required

# install the stable chef-dk.  Use chef-current-precise to install the pre-release chef-dk release.
addons:
  apt:
    sources:
      - chef-stable-precise
    packages:
      - chefdk

services: docker

env:
  matrix:
  - INSTANCE=servernode-ubuntu-1604
  - INSTANCE=servernode-ubuntu-1404
#  - INSTANCE=servernode-ubuntu-1204
#  - INSTANCE=servernode-centos-8
#  - INSTANCE=servernode-centos-7

# Don't `bundle install`
install: echo "skip bundle install"

# Ensure we make ChefDK's Ruby the default
before_script:
  # https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142230889
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/embedded/bin/chef gem install kitchen-docker
script:
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/rubocop --version
#  - /opt/chefdk/embedded/bin/rubocop
  - /opt/chefdk/embedded/bin/foodcritic --version
#  - /opt/chefdk/embedded/bin/foodcritic . --exclude spec
  - /opt/chefdk/embedded/bin/foodcritic -f correctness .
#  - /opt/chefdk/embedded/bin/rspec
  - KITCHEN_LOCAL_YAML=.kitchen.docker.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}

branches:
  only:
    - master
